### ISSUE TITLE
Class GCI should go to its own model

### ISSUE THREAD

**Issue by danielfireman** [gcinterceptor/gci-simulator#3]
This is me being strict here, but GCI is a server interceptor. It uses the call to force a GC, but besides that, they are completely decoupled. It is much more related to the server module than to the gc module.

https://github.com/gcinterceptor/gci-simulator/blob/5d7a5c98241bf0df82ce2342302db98ab199c25d/modules/garbage.py#L59:7

**Comment by dfquaresma** [comment]
For now, the server contains a instance of gc and gci.  Both run independetly of the server. 
GCI is not intercepting the requests directly, but for each request arrieved the server calls GCI to make his analyzes. In parallel, the GCI periodically make his checks. 
The call commented is here: https://github.com/gcinterceptor/gci-simulator/blob/simulator-test/modules/server.py#L55
And the periodical check is here: https://github.com/gcinterceptor/gci-simulator/blob/simulator-test/modules/garbage.py#L60
Thanks for help. If there is any thing to say, please share with us.

**Comment by danielfireman** [comment]
> In parallel, the GCI periodically make his checks.

At a first glance, this sounds strange to me. It is strange because in real life GCI is **not** an active entity. It does not check anything by itself. It is only activated when a request arrives.

Following the code, I found [this snippet](https://github.com/gcinterceptor/gci-simulator/blob/simulator-test/modules/garbage.py#L61). Which brings us to [here](https://github.com/gcinterceptor/gci-simulator/blob/simulator-test/modules/garbage.py#L61), which looks like what GCI should do. 

So, could you please explain why do we activate GCI periodically **and** when a request is called? I mean, why to deliberately add complexity and get the mode more distant from real life?

cc/ @thiagomanel

**Comment by dfquaresma** [comment]
@thiagomanel commented it earlier and in fact I agree with you too. The only reason for that logic is because the GCI only calls the GC when another request arrived. For example:
I have received a request that demands 35% of the heap. After that, I have received another wich costs the same. Now, the heap should be at 70% and GCI would run GC. Without a periodical check, GCI wouldn't start GC until another request arrived.
@thiagomanel explained to me why there is no problem on that.
I'm going to update that right now. Thanks again.

**Comment by dfquaresma** [comment]
> The only reason for that logic is because the GCI only calls the GC when another request arrived.
I mean the GCI of the simulator...

**Comment by dfquaresma** [comment]
> The only reason for that logic is because the GCI only calls the GC when another request arrived.

I mean the GCI of the simulator...

**Comment by danielfireman** [comment]
> I have received a request that demands 35% of the heap. After that, I have received another wich costs the same. Now, the heap should be at 70% and GCI would run GC. Without a periodical check, GCI wouldn't start GC until another request arrived. @thiagomanel explained to me why there is no problem on that.

That's not only fine, that is the **correct** behavior :smile: 

Thanks for updating it!
