### ISSUE TITLE
Shedded request face the same host.

### ISSUE THREAD

**Issue by dfquaresma** [gcinterceptor/gci-simulator#32]
There is a chance of a request shedded be foward to the same server that shedded it. It can be noted [here](https://github.com/gcinterceptor/gci-simulator/blob/master/models/loadbalancer.py#L49). If we want to change this we should treat shedded requests in another point of view. The question is: do we want it? The need of that may vary to load balancer to load balancer.

**Comment by danielfireman** [comment]
Ou focus is  [nginx](https://www.nginx.com/). The main directives here are [proxy_next_upstream](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream), [proxy_next_upstream_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream_timeout) and [proxy_next_upstream_tries](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream_tries). Those pretty much rule the behavior we have in your current experiments.
