### ISSUE TITLE
Should we start by simulating the core algorithm that GCI implements? 

### ISSUE THREAD

**Issue by dfquaresma** [gcinterceptor/gci-simulator#6]
All GCI's implementations as gci-go, gci-python or gci-java, although runtime environment details, are the implementations of a core algorithm. They're aimed at reduce the service time. 
So, if we simulate the core algorithm, not inicialy considering each runtime, and prove that it can reduce the latency in cloud servers,  how much steps foward have we made? I mean, what that conclusion suggests for scenarios considering a especific runtime enviroment?
My intention here is think about how could we get results that could be useful to approve GCI's implementations even for nonexistent languages yet and make easier the approving of a especific implementation.

**Comment by danielfireman** [comment]
> All GCI's implementations as gci-go, gci-python or gci-java, although runtime environment details, are the implementations of a core algorithm. They're aimed at reduce the service time.

Being annoyingly strict here (just to make sure we´re all on the same page): they´re aiming reduce the **tail** of the service time.

> So, if we simulate the core algorithm, not inicialy considering each runtime, and prove that it can reduce the latency in cloud servers, how much steps foward have we made? I mean, what that conclusion suggests for scenarios considering a especific runtime enviroment?

Reducing the latency using GCI compared to what? How could you be precise comparing GCI with the bare runtime if you don´t implement the runtime?

That said, I believe abstracting out the runtime is useful to verify improvements on parts of the GCI implementation. For instance, imagine if we propose a new algorithm to estimate the unavailabity period. Then we could compare the current version and the new version assuming that both are sitting on top of the same runtime mode.

> My intention here is think about how could we get results that could be useful to approve GCI's implementations even for nonexistent languages yet and make easier the approving of a especific implementation.

Your question led me to another question: assuming that GCI implementations are dependent on the runtime, how can you validate a language-specific GCI implementation without modelling the runtime?

I mean, Go and Java GCI implementations are different and the difference sits on the runtime specifics. For instance, the Go runtime allows us to switch the GC off whereas the Java runtime does not.

**Comment by dfquaresma** [comment]
> Reducing the latency using GCI compared to what? How could you be precise comparing GCI with the bare runtime if you don´t implement the runtime? 

My intention here is to think if we can do it without the runtime looking only for the core algorithm that all GCI's implementations will use and, If we could do it, analize what we can take from the results. Note that i'm suggesting it only as a initial and generated simulation. 

> Your question led me to another question: assuming that GCI implementations are dependent on the runtime, how can you validate a language-specific GCI implementation without modelling the runtime?

I agree with you. I can't see now how validate a language-specific GCI implementation without modelling the runtime and that's my point here. Assuming that, what can we take from results based on generated simulations even for that especific scenarios? 

If there isn't a way to do it, we can close the issue.
